### ISSUE TITLE
Test the latest PyDP

### ISSUE THREAD

**Issue by PatrickHunter** [OpenMined/PyStatDP#1]
## Description
Validate the new release of PyDP
## Type of Test
- [ ] **Integration test** (e.g. checking if a certain group or set of functionality is working as intended)

## Expected Behavior
All algorithms except dp_bounded_standard_deviation should pass validation.
## Additional Context
PyDP has gone through a major update and needs to be retested

**Comment by Harkirat155** [comment]
resolved at test, api testing to be finalized at #6 .
