### ISSUE TITLE
Fix benchmarkMinimal to run after refactor

### ISSUE THREAD

**Issue by PatrickHunter** [OpenMined/PyStatDP#8]
## Description
benchmarkMinimal does not run
## How to Reproduce
1. Got to the top level directory of the PyStatDP repo
2. python3 benchmarkMinimal.py
3. `Traceback (most recent call last):
  File "benchmarkMinimal.py", line 33, in <module>
    from pystatdp import detect_counterexample, ONE_DIFFER, ALL_DIFFER
ImportError: cannot import name 'detect_counterexample' from 'pystatdp' (/Users/patrickhunter/openmined/statdp/pystatdp/__init__.py)
`

**Comment by Harkirat155** [comment]
This was refactored. 
the correct way to import `detect_counterexample` is 
```
#import pystatdp class from the module
from pystatdp import pystatdp
#class initiation
psd = pystatdp()
#detect_counterexample
psd.detect_counterexample(...)
```
